### ISSUE TITLE
Field Layout: Matrix, no Info in collapsed accordion

### ISSUE THREAD

**Issue by thomasbendl** [engram-design/SuperTable#458] opened 2022-03-30 10:34 UTC
When using a Super Table Field in an Matrix Field, where the Super Table Field Layout is set to Matrix no info text is shown in the collapsed Super Table Field (accordion)

<img width="718" alt="Bildschirmfoto 2022-03-30 um 12 30 54" src="https://user-images.githubusercontent.com/8804216/160811937-202094fe-10b7-448f-b494-7924161aea20.png">

**Additional info**
- Plugin version: 2.7.1
- Craft version: 3.7.37
- Multi-site: No

**Comment by evanwarner** [comment] 2022-04-07 17:01
This is a dupe of #439. @thomasbendl I proposed the solution in that issue, which you can implement yourself until the plugin source is updated.

**Comment by engram-design** [comment] 2022-10-18 08:05
Fixed in [3.0.3](https://github.com/verbb/super-table/releases/tag/3.0.3)

**Closed as completed by engram-design** 2022-10-18 08:05 UTC
