### ISSUE TITLE
twig searchquery not working anymore on supertable elements

### ISSUE THREAD

**Issue by RainerZarth** [engram-design/SuperTable#382] opened 2020-09-01 15:03 UTC
**Description**
When searching through entries with twig query
{% set searchQuery = craft.app.request.getParam('q') %}
{% set result = craft.entries().section("sectionhandle").search(searchQuery).orderBy("score").all() %}
the result is no longer finding content of fields when nested in a Supertable. Normal matrix works fine.
this worked before at Craft version 3.4.25 and Supertable 2.5.1 (old version with postgres db)
with the new versions of craft and supertable it finds nothing, sadly.
i already tried to rebuild search index with `php craft resave/entries --update-search-index` didnt help

**Steps to reproduce**
1. Put a supertable field inside a Matrix block
2. put a matrix field inside the supertable
3. put a texteditor (redactor) inside the nested matrix
4. create entry with that matrix and add richt text into the editor field
5. create search field like the documentation ([https://craftcms.com/docs/3.x/dev/examples/search-form.html](https://craftcms.com/docs/3.x/dev/examples/search-form.html))
search a word in content, result will be null

**Additional info**
- Plugin version: supertable 2.6.2, redactor 2.7.3
- Craft version: 3.5.7
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment] 2020-09-05 07:50
I can't seem to replicate this, and have put together an example with each variation: https://d.pr/i/fTpkLw

Then, using the Twig you've mentioned, the entry is returning a result for each search query. It might be tricky to find, but if you can have a look in your `searchindex` table for the values you're adding to test searchability?

Anything I'm doing wrong on my end?

**Comment by engram-design** [comment] 2020-09-05 07:56
I just re-read your reproducing steps. Just to confirm, this is for a Matrix > Super Table > Matrix field setup? If so, I can reproduce for just that case. I'm not quite sure what we can do in that scenario.

**Comment by engram-design** [comment] 2020-09-05 08:07
Actually (sorry for the replies), now it seems to be matching correctly. For example: https://d.pr/i/OC1Ik2 - so not sure what's going on...

**Comment by engram-design** [comment] 2021-05-19 03:36
Closing due to age

**Closed as completed by engram-design** 2021-05-19 03:36 UTC
