### ISSUE TITLE
SuperTable creates new elements for every block on every entry save

### ISSUE THREAD

**Issue by evanwarner** [engram-design/SuperTable#432] opened 2021-10-06 07:59 UTC
I looked a little deeper into #420 and I think this bug is indicative of a bigger problem, likely with roots in Craft 3.7 changes. To verify, I kicked up a test in an old sandbox and incrementally updated Craft. #420 started occurring the instant I jumped from Craft 3.6.18 to 3.7.

Super Table remembers which blocks to keep collapsed by storing their IDs in localStorage. This led me to watch a set of elements while saving an entry...the block IDs all changed. Not just the blocks in an edited Super Table field...but every single Super Table block in the edited _entry_ received new IDs (in fact you don't even have to edit a Super Table field at all for this to occur). I verified that my `supertableblocks` table in the database was indeed growing by leaps and bounds on every entry save: additional records for every Super Table block on the edited entry. Each of these corresponded to a new record in the `elements` table as well.

My theory is that this has to do with revisions. Craft 3.7 introduced the concept of a canonical entry: the source element/id that doesn't change when each revision is saved. The records in `supertableblocks` show that the `ownerId` column is constantly changing, while in the `elements` table, the `canonicalId` column is staying consistent for Entry and MatrixBlock records. So maybe Super Table is thinking every entry save is a brand new entry?

**Steps to reproduce**
1. Create an entry that has a Super Table field.
2. Edit and re-save the entry.
3. Observe the new records in the `supertableblocks` and `elements` database tables.

**Additional info**
- Plugin version: 2.6.8
- Craft version: 3.7 or higher

**Comment by aelvan** [comment] 2021-10-06 12:36
Can confirm that I also see this behaviour. Saving an entry with a supertable in it (inside a matrix), without changing any content, generates new rows in the related supertable database table equal to 2x the number of supertable elements I have in the entry (probably 2x because I have two languages). 

Plugin version: 2.6.8
Craft version: 3.7.15

**Comment by mmikkel** [comment] 2021-10-07 07:10
I can also confirm this behaviour. Performance when saving entries also seem noticeably slower once there's a few SuperTable blocks in there; possibly this issue is related to #423?

Plugin version: 2.6.8
Craft version: 3.7.16

**Comment by evanwarner** [comment] 2021-10-07 18:04
Yeah, I'm really suspecting this is also the source of people's recent observations of slow entry editing with Super Table.

**Comment by OwenMelbz** [comment] 2021-10-14 14:30
Hi,

Is there any progress on this please as we're also experiencing this problem?

Thanks

**Comment by laurabennett** [comment] 2021-10-20 14:07
Not sure if this is the same or a related issue... but when I updated to latest versions of Craft and Super Table the data in my entries changed. LUCKILY I was able to go back to a previous draft that did have the correct data, but Yikes not cool!!

**Comment by evanwarner** [comment] 2021-11-02 18:35
@engram-design Wondering if we can get your thoughts on this issue, and if it's as significant as it seems? With the news that nested matrix won't be coming in Craft 4, Super Table is going to stay very necessary for the next year.

**Comment by engram-design** [comment] 2021-11-03 07:44
@laurabennett Indeed concerning, not _quite_ sure if that's the same issue. Can you recall what version of Craft you were updating from (roughly)?

@evanwarner I thought nested Matrix was on the cards for Craft 4, but maybe I wasn't listening close enough at DotAll.

I'm been porting over a number of content changes caused by Craft 3.7+ changes, and would be great if you're able to test these out. To get the fixes early, change your `verbb/super-table` requirement in `composer.json` to:

```
"require": {
  "verbb/super-table": "dev-craft-3 as 2.6.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by laurabennett** [comment] 2021-11-03 16:34
"craftcms/cms": "3.7.16",
    "verbb/super-table": "2.6.8",

**Comment by evanwarner** [comment] 2021-11-03 19:00
@engram-design Ah I guess I was sort of reading between the lines at this part of the talk: https://vimeo.com/637691328#t=2183s, where Brandon says nested matrix is a can of worms.

I'll definitely test that dev branch ASAP and let you know if I see improvements. Thanks for the response!!!

**Comment by engram-design** [comment] 2021-11-30 11:31
Should be fixed in [2.7.0](https://github.com/verbb/super-table/releases/tag/2.7.0)

**Closed as completed by engram-design** 2021-11-30 11:31 UTC

**Comment by joshuapease** [comment] 2021-12-03 17:10
Thanks for that update @engram-design. Is there any sort of cleanup that we could / should (or maybe shouldn't) try and do to remove the excessive supertable fields. 

Would just pruning revisions be enough of a fix?

**Comment by evanwarner** [comment] 2021-12-03 22:52
The 2.7.0 update does not change the behavior I reported. Every entry save still creates a new `supertableblocks` and `elements` record for every block. Here's a DB sample from a page with one top-level ST field with 4 blocks, and one ST field nested in a matrix, also with 4 blocks. You can see the pattern of new blocks being created (newest records at top).

It looks like the ST elements now correctly track a canonical ID, but they're still getting duplicated on a mass scale. Maybe I'm missing something...is this just how Craft works now with revisions? If so it seems hugely wasteful of DB space and write cycles.

### `supertableblocks` table:

<img width="708" alt="supertableblocks" src="https://user-images.githubusercontent.com/6453842/144682585-9559e494-8cda-46f7-a065-95691c5b0160.png">

### `elements` table:

<img width="1060" alt="elements" src="https://user-images.githubusercontent.com/6453842/144682588-7720d66b-d10c-4a41-94d2-2aea54207713.png">
