### ISSUE TITLE
superTableBlockTypes in project.yaml are getting removed on project sync

### ISSUE THREAD

**Issue by nettum** [engram-design/SuperTable#280] opened 2019-06-26 18:16 UTC
### Description
I've updated some field-settings inside a super-table in a matrix.
After committing the changes I'm dumping the stage database to dev to test my changes.
Then running `./craft migrate/all` and after running `./craft project-config/sync` (or doing it on the first cp request) some of the superTableBlockTypes are getting removed from `project.yaml`.
This result in super-table fields inside the matrix that are now either missing or are old versions.

Is this expected? Shouldn't project config be the source of truth?

See screenshots below:  
![01-stbf](https://user-images.githubusercontent.com/798156/60202688-6cfd0080-984b-11e9-8dba-c28926c0a1ae.png)

![02-stbf](https://user-images.githubusercontent.com/798156/60202717-7edea380-984b-11e9-80da-b9ccdd8f9c53.png)

If I try to discard the changes after project sync have removed stuff from `project.yaml` and manually bump the timestamp in `project.yaml` I'm getting the following error when I try to sync changes again:
![03-stbf](https://user-images.githubusercontent.com/798156/60202852-c7965c80-984b-11e9-87df-f58eab940d0d.png)

Before all this occurred I had to manually fix some things because of a merge conflict in `project.yaml`, so this _may_ be an edge-case because of something I've done. I'm going to recheck project yaml again to see if I find any mistakes.  

If I set up a empty database and run `./craft setup` it will sync the changes from `project.yaml` without any errors or remove stuff and everything looks correct in cp.

Could it be related to the latest project config changes from P&T in 3.1.32 (which did alot of changes/rearranging to my `project.yaml` file:
> Project Config now sorts arrays when all of the keys are UIDs.

Any thoughts on this? I'm on discord if you need more info or project.yaml/dbdump.

### Additional info

- Plugin version: 2.1.20
- Craft version: 3.1.32.1

**Comment by nettum** [comment] 2019-06-26 18:23
Also did a test to set `allowAdminChanges => false` locally before running `./craft project-config/sync`. Got the following error since it still try to change `project.yaml`:
`Applying changes from project.yaml ... error: Changes to the project config are not possible while in read-only mode.`

**Comment by nettum** [comment] 2019-07-01 17:26
FYI:
Versions on stage are Craft CMS 3.1.27 and Super Table 2.1.19.
Local versions are 3.1.32.1 and 2.1.20.

I kind of got this working again locally.  
I had to empty `config` and `configMap` in the `info`-table:
  
1) Import stage database to local dev
2) Empty `config` and `configMap` fields in db.
3) Run `./craft migrate/all` and `./craft project-config/sync --force`
4) Verify that admin looks correct and no changes to project.yaml.

Running `./craft project-config/sync --force` without empty `config` and `configMap` did not work (so somewhat related to https://github.com/craftcms/cms/issues/4464).  
It removed stuff from project.yaml instead of writing it to the database.  
Still not 100% sure how I ended up in this state, but project config file looks correct and after going throught steps 1-4 admin looks good and Check Content Tables says No errors found.

**Comment by ryanpcmcquen** [comment] 2019-07-01 17:28
@nettum, please help vote up my PR: https://github.com/craftcms/cms/pull/4465

**Comment by nettum** [comment] 2019-07-01 18:06
Hi @ryanpcmcquen!
As for this issue I need to understand *why* things breaks first and then we can start looking at solutions (and where that solution is!).  

Is it my workflow? If so - what am I doing wrong - and what should I do instead?  
Is it a migration or something in super-table that cause this?  
Is it some logic in craftcms when running project sync that's not working as expected?  

For this exact case I'm mostly puzzled that `./craft project-config/sync --force` is removing stuff from project.yaml instead of beeing the "source of truth".

Lets see if support over at Pixel & Tonic can find anything regarding your issue. :+1:

**Comment by ryanpcmcquen** [comment] 2019-07-01 19:17
Well, for reference, we are not even using Super Tables and have run into this issue multiple times.

**Comment by nettum** [comment] 2019-07-04 15:02
Seems like emptying `config` and `configMap` didn't solve it completely.  

I think one of the reasons things may have blown up in my case is that I've *changed* the field type for one field and removed another one inside a supertable inside a matrix.

Take this commit diff:  
changed field type:  
![image](https://user-images.githubusercontent.com/798156/60671734-05126f80-9e74-11e9-8917-536c50fe779f.png)  
removed field:  
![image](https://user-images.githubusercontent.com/798156/60672632-25dbc480-9e76-11e9-9fc8-64906da8646d.png)


After I emptied `config` and `configMap` and run migrations and syncing project yaml it looks right in admin, but I do get an error when I try to save an entry with the new supertable that now have 2 fields instead of 3 (1 removed, 1 changed, 1 untouched):  
old supertable:  
![image](https://user-images.githubusercontent.com/798156/60673073-39d3f600-9e77-11e9-8a90-bd13bd5a0639.png)

new supertable:  
![image](https://user-images.githubusercontent.com/798156/60675164-021b7d00-9e7c-11e9-8ea5-1518f6c2f47d.png)



error (if I try to add rows for the supertablefield that have been changed):  
![image](https://user-images.githubusercontent.com/798156/60672990-fed1c280-9e76-11e9-9f6a-c7720d27ee91.png)

There are no references to `icon` inside my `project.yaml`.  
Will do some testing to see if I can get the same error on a fresh craft install to verify.

Check Content Tables still says "No errors found" and resaving ST-fields didn't seem to help.

**Comment by ryanpcmcquen** [comment] 2019-07-04 22:30
We switched from Super Tables to Matrix fields because of issues like this.

**Comment by engram-design** [comment] 2019-07-14 07:32
@nettum Thanks for the detailed post here! I'm going to set up a few test cases to get this to a reproducible state. For what its worth - we have had these sort of project config issues for a while, and its incredibly frustrating - issues similar to this, but unrelated to Super Table.

Might follow up in Discord!

**Comment by nettum** [comment] 2019-07-14 09:24
All right, thanks. Can confirm that I have no problems saving entries with the new fields inside ST when setting up the project with a empty database. `./craft setup` runs `> applying existing project config ... done` and everything seems ok. So that's all good - now just have to figure out how to get our stage/prod synced up correctly again.

So I guess _something_ have happen during update and project config sync of craft / supertable versions.  
And yes, I was unsure if this was a craft or supertable issue, but as it only affected ST-fields I posted it here. That being said - I have a feeling there are still some quirks with project config that needs to be fixed, so this may be a underlying issue on how the workflow for project config and syncing works in some cases.

**Comment by nettum** [comment] 2019-07-14 10:23
FYI - Did an update on the clean install:
```
- craft 3.1.33 => 3.1.34
- super-table 2.1.20 => 2.1.21
```
Then drop local db, dumping stage to local and ran migrate and project sync with --force.
Result: the whole `superTableBlockTypes`key and content is gone from `project.yaml` and I'm missing the fields inside ST inside the matrix.

**Comment by nettum** [comment] 2019-07-31 09:18
So, to _try_ to fix this and to be sure I didn't do anything weird the first time I did the following:

1) Checkout project in a new folder, create new branch and an empty database
2) Dump stage database to the empty local db
3) Reset composer.json, composer.lock and project.yaml to the same versions as stage (craft 3.1.27 and super-table 2.1.19)
4) Run composer install
5) Update craft to newest 3.1.x and update all plugins (craft 3.1.34.2 and super-table 2.1.21)
6) Do all (settings-)changes manually since last stage deploy and verify that project.yaml looks correct for each step. Along the way things looks correct.
7) After all changes are done and commited, drop local database and dump stage db to local db again to verify that next stage deploy will not blow up
8) Run `./craft migrate/all` and `./craft project-config/sync --force` locally.
9) Confirm that superTableBlockTypes still are getting removed :(

![image](https://user-images.githubusercontent.com/798156/62199300-84b43100-b383-11e9-81df-1e0bc1215737.png)
![image](https://user-images.githubusercontent.com/798156/62199374-a6151d00-b383-11e9-8704-4a1ee0eb3609.png)
![image](https://user-images.githubusercontent.com/798156/62199582-099f4a80-b384-11e9-869b-21d21a1ef41a.png)

Here are the fields:  
![image](https://user-images.githubusercontent.com/798156/62199813-7d415780-b384-11e9-8758-74d3185838e2.png)

**Comment by engram-design** [comment] 2019-09-11 10:24
Thanks for the excellent detail as always @nettum I followed your instructions exactly, and couldn't seem to replicate it. I'm wondering if you could share your project.yaml file to test locally (hit me up on Discord to share if you like)

**Comment by engram-design** [comment] 2020-07-27 10:26
Closing due to age.

**Closed as completed by engram-design** 2020-07-27 10:26 UTC
