### ISSUE TITLE
Saving draft deletes content in SuperTable

### ISSUE THREAD

**Issue by jeffaglenn** [engram-design/SuperTable#402] opened 2021-02-11 17:45 UTC
If an entry has a Super Table field with content in it and the entry is saved as a draft both the "current" draft and saved draft lose its content.

**Steps to reproduce**
1. Edit entry with Super Table field
2. Save entry as a draft
3. Return to entries page
4. Edit the same entry - the content is gone

**Additional info**
- Plugin version: 2.6.7
- Craft version: 3.6.5.1
- Multi-site: No

![supertable](https://user-images.githubusercontent.com/34280463/107676140-6dcfe980-6c5e-11eb-867d-3b7226cb57d2.gif)

**Comment by engram-design** [comment] 2021-02-13 04:55
I can't seem to replicate this, refer to my video below.

https://user-images.githubusercontent.com/1221575/107841974-c8f70d00-6e13-11eb-8039-641bdeece752.mov

Any other plugins installed? I know plugins like Preparse messes up with saving Super Table/Matrix/Neo blocks.

**Comment by mcurry1213** [comment] 2021-02-17 15:54
I can confirm. This is happening to me now. Interestingly enough, some fields save, some do not. I have partial content in a redactor field save, but not all content.

**Comment by jeffaglenn** [comment] 2021-02-18 18:09
Just did a clean install and wasn't able to recreate. I'm doing more digging to see what might be the issue. 

It's only happening with drafts and Super Table which is odd. I know Craft just changed how drafts work and all of this started happening with one of the recent updates. Anything I could try to help narrow it down?

**Comment by mcurry1213** [comment] 2021-02-18 20:52
I updated Craft just now and couldn't replicate the issue. I did read a lot of commotion about the Craft draft update over on discord, so it may be related since that's what the latest update seemed to address.

**Comment by engram-design** [comment] 2021-02-19 06:04
Hmmm... It might be worth running the content table checker/fixer, but I'll see what I can do. I might need to offer some manual debugging steps once I've figured out where the best breakpoints are.

But it does certainly sound related to the Craft draft update mechanisms, although nothing has really changed for Matrix (Super Table being functionally similar).

**Comment by LeoWie93** [comment] 2021-02-19 12:50
Im having the same problem in Craft `v3.5.19`. But it only occurs if an required field was left empty the first save.

- The Field is marked as "required" to the user. 
- Filling the field out and saving again gives the "required" error message again.
- Filling out the field a second time and saving for the third time saves the entry. But empties all matrix content inside the entry itself.

**Comment by brandonkelly** [comment] 2021-10-26 19:04
We came across a similar issue, which occurred when there were Matrix/Super Table/Neo blocks on the page that had the same IDs as Super Table block _types_. That’s now fixed in Craft 3.7.18 (https://github.com/craftcms/cms/commit/4d992d6c34cbe9cba1c6c4568c2f3ca957527657). Not sure if it’s the same issue you folks are experiencing here, since it’s pretty unlikely to happen for entries with larger IDs like the ones I’m seeing in these videos, but worth mentioning here anyway.

**Comment by engram-design** [comment] 2021-11-03 08:03
Thanks for the comment @brandonkelly, good to know. Going to close this for now.

**Closed as completed by engram-design** 2021-11-03 08:03 UTC
