### ISSUE TITLE
Stop closing issue related to project config.

### ISSUE THREAD

**Issue by jesuismaxime** [engram-design/SuperTable#253] opened 2019-03-13 21:04 UTC
We experienced many bugs with this plugin when it comes to project.yaml (sync through multiple environments, etc.).

The last one : 

1. add a new SuperTable field in the CP;
2. Go to an existing Section and add the new field in the field layout **;
3. Save the Section
4. Tadam. The field is no more available in the section AND the CP.

** This behavior also appear when add the (new) SuperTable field in a Neo field.

**Comment by engram-design** [comment] 2019-03-14 05:55
The only reason we're closing issues is because they're seemingly being fixed, usually following up with the poster on Discord to confirm.

I'm afraid I can't reproduce this behaviour, and its the first I've heard of this particular issue. Was this a brand new Craft site to begin with, or an upgraded one (From 3.x or 2.x)? When you save the Super Table field, does it appear in your project.yaml file?

I also assume you're on the latest versions of Craft and Super Table?

**Comment by engram-design** [comment] 2019-05-11 06:09
I'm closing this as its been some time without a response or update. Please let me know if you'd like this re-opened, or is someone else is experiencing this issue.

**Closed as completed by engram-design** 2019-05-11 06:09 UTC
