### ISSUE TITLE
[Craft 4] SuperTable field setting changes not saving

### ISSUE THREAD

**Issue by mediagirl** [engram-design/SuperTable#472] opened 2022-06-05 22:53 UTC
I'm having two issues.

**NOTE**: This support request is for a field I imported using the Field Manager plugin.

1 Changes I'm making to settings for Super Table fields inside this imported Matrix field are NOT saving.

2 In order to fix the saving issue, I'm using the "Check Content Tables" button on the plugin page. It reports 2 errors:

```
> ERROR: {{%stc_13_boxes}} has missing field columns ...
> ERROR: {{%stc_14_contentrow}} has missing field columns ...

```

I click the "Fix Content Tables" button and the fix seem to complete"

```
> Content table {{%stc_13_boxes}} field columns have been corrected ...
> Content table {{%stc_14_contentrow}} field columns have been corrected ...
```

However, when I go back to "Check Content Tables", the same errors show up again and again. The errors are never fixed.

**Additional info**
- Plugin version: 3.0.0-beta.4
- Craft version: 4.0.4
- Multi-site: No

**Comment by engram-design** [comment] 2022-06-05 23:29
Can you try the latest `craft-4` branch with a fix for this? Change your `verbb/super-table` requirement in `composer.json` to:

```
"require": {
  "verbb/super-table": "dev-craft-4 as 3.0.0-beta.4",
  "...": "..."
}
```

Then run `composer update`.

As for the content table checker, that'd likely to be retired for Craft 4, as this was to ease a transition from Craft 2 > Craft 3, and some of the minor updates in the 3.x release cycle that were in fact major updates for things like project config. You shouldn't need to use the content table checkers going forward.

**Comment by mediagirl** [comment] 2022-06-06 01:23
Your fix did the trick! Many thanks for looking at that so quickly. I really appreciate your time... And your field is my favorite:) I use it on every project.

**Comment by engram-design** [comment] 2022-06-06 01:24
No problem, and thanks for the kind words!

**Comment by mediagirl** [comment] 2022-06-06 01:27
One thing since I have your attention... 

For every project I make this one CSS change... I change the vertical alignment for the TD to TOP instead of MIDDLE. It helps make the content more readable for me when editing.

**Comment by engram-design** [comment] 2022-06-06 01:29
Could you shoot through a screenshot of before/after? Just need to know what layout you're using.

**Comment by mediagirl** [comment] 2022-06-06 01:31
This one:
https://dl.dropboxusercontent.com/s/xb3kmyb172tpwkd/2022-06-05_19h30_46.png?dl=0

**Comment by mediagirl** [comment] 2022-06-06 20:56
My issue with saving SuperTable field changes (when inside a Matrix) field was fixed yesterday when I tested after applying your changes, but it's happening again today oddly. 

I created a new SuperTable field today inside a Matrix field and now my changes to the field (specifically name and handle) are not savings.

Any ideas?

**Comment by ellukesmith** [comment] 2022-06-07 02:03
We're having the same issue. 

We were already running off the craft-4 branch, so we just ran `composer update` which seemed to fix the issue the first time we updated a nested supertable field, but the next time we attempted it it was the same result as before - nothing updated.

~~I have noticed our main issue is with a Supertable nested inside a Matrix nested inside a Supertable nested inside a Matrix. The first nested Supertable seems to be updating correctly for us at the moment.~~

EDIT: Scratch that, what I'm finding is that any Supertable field nested inside a matrix will do the following:

1. Creating the field saves correctly.
2. Updating the field after the first save will save correctly.
3. Updating the field after the second save **will not save correctly.**
4. Any follow up attempts will not save.
5. Deleting the field works.

I think the issue is worse when you have a Supertable within a Matrix within a Supertable within a Matrix, as the top level Supertable field will stop updating, and then all nested fields will stop updating also (which impacts creating new fields and deleting old fields).

**Comment by engram-design** [comment] 2022-06-07 12:36
Closing this and following up in already added issue https://github.com/verbb/super-table/issues/473

**Closed as not planned by engram-design** 2022-06-07 12:36 UTC

**Comment by engram-design** [comment] 2022-06-08 03:25
I will also make the comment @ellukesmith that only 3 levels of nesting is supported, and that's strictly Matrix > Super Table > Matrix. Anything more than that is likely going to [cause issues](https://github.com/verbb/super-table#updating-to-craft-35).

**Comment by mediagirl** [comment] 2022-06-08 18:11
My issue is with a Matrix > Super Table nesting setup. The changes I make to the fields inside the Super Table don't update.
