### ISSUE TITLE
Migration Issue with 2.0.4 Update

### ISSUE THREAD

**Issue by mikestecker** [engram-design/SuperTable#128] opened 2018-02-20 16:46 UTC
### Description
After updating from 2.0.3 -> 2.0.4 I'm getting this error when going through the migration:

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX craft_stc_24_sectioncalltoactionbutton_elementId_locale_fk; check that it exists
The SQL being executed was: DROP INDEX craft_stc_24_sectioncalltoactionbutton_elementId_locale_fk ON craft_stc_24_sectioncalltoactionbutton

Migration: verbb\supertable\migrations\m180219_000000_sites

Output:

> create unique index craft_stc_22_features_elementId_siteId_unq_idx on craft_stc_22_features (elementId,siteId) ... done (time: 0.006s)
> add foreign key craft_stc_22_features_siteId_fk: craft_stc_22_features (siteId) references {{%sites}} (id) ... done (time: 0.063s)
Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX craft_stc_24_sectioncalltoactionbutton_elementId_locale_fk; check that it exists
The SQL being executed was: DROP INDEX craft_stc_24_sectioncalltoactionbutton_elementId_locale_fk ON craft_stc_24_sectioncalltoactionbutton 
```

In the meantime, I went back and version locked my composer to 2.0.3... Let me know if you want me to send you my database.

If it helps, just yesterday I added a second site to my Craft install (not multi-locale, but a second site) and then I removed it. I'm curious if this may have caused some strange issue?

### Steps to reproduce

1. Ran `composer update` to update from 2.0.3 to 2.0.4
2. Return to Craft in browser, run migration

### Additional info

- Plugin version: 2.0.4
- Craft version: Craft 3 RC10.1

**Comment by florentineprinzessinzusachsen** [comment] 2018-02-20 17:17
I can confirm this on my installation (freshly imported database from a 2.6 installation).

Same config as above. My site has 5 locales.

`Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'craf_supertableconte_58_headlinesubheadlinebut_elementI_local_fk'; check that column/key exists
The SQL being executed was: DROP INDEX craf_supertableconte_58_headlinesubheadlinebut_elementI_local_fk ON craft_supertablecontent_58_headlinesubheadlinebutton
Migration: verbb\supertable\migrations\m180210_000000_migrate_content_tables`

When the table has the following structure:

```
CREATE TABLE 'craft_supertablecontent_58_headlinesubheadlinebutton' (
  'id' int(11) NOT NULL,
  'elementId' int(11) NOT NULL,
  'locale' char(12) COLLATE utf8_unicode_ci NOT NULL,
  'locale__siteId' int(11) NOT NULL,
  'field_headline' text COLLATE utf8_unicode_ci,
  'field_subheadline' text COLLATE utf8_unicode_ci,
  'field_colorHeadlineSubheadline' varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  'field_buttonLink' text COLLATE utf8_unicode_ci,
  'field_buttonIcon' varchar(255) COLLATE utf8_unicode_ci DEFAULT 'none',
  'field_position' varchar(255) COLLATE utf8_unicode_ci DEFAULT 'middleCenter',
  'field_showPostDate' tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  'dateCreated' datetime NOT NULL,
  'dateUpdated' datetime NOT NULL,
  'uid' char(36) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE 'craft_supertablecontent_58_headlinesubheadlinebutton'
  ADD PRIMARY KEY ('id'),
  ADD UNIQUE KEY 'craf_supertablecont_58_headlinesubheadlineb_element_local_un_id' ('elementId','locale'),
  ADD KEY 'craft_supertablecontent_58_headlinesubheadlinebutton_locale_fk' ('locale'),
  ADD KEY 'craft_supertableconte_58_headlinesubheadlinebutt_local_siteI_fk' ('locale__siteId');
```

**Comment by engram-design** [comment] 2018-02-21 00:16
Thanks for this, after much investigation, it looks like there's a slight issue with Craft itself returning out of date indexes when trying to delete them, causing this error.

Before I push a new release (or at least, revert the 2.0.4 release), are you able to try the latest master out via `composer require verbb/super-table:dev-craft-3`

This also seems to be an issue with longer table names (the field handles), where their indexes get truncated.

**Comment by mikestecker** [comment] 2018-02-21 00:29
@engram-design thanks for the update... still having errors when using `dev-craft-3`:

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX craft_stc_24_sectioncalltoactionbutton_elementId_locale_fk; check that it exists
The SQL being executed was: DROP INDEX craft_stc_24_sectioncalltoactionbutton_elementId_locale_fk ON craft_stc_24_sectioncalltoactionbutton

Migration: verbb\supertable\migrations\m180219_000000_sites
```

do you think my issue has to do with the truncation problem you mentioned?

**Comment by engram-design** [comment] 2018-02-21 03:13
@mikestecker If you're able to give this a go (one last time hopefully) and let me know? 

`composer require verbb/super-table:dev-craft-3`

**Comment by mikestecker** [comment] 2018-02-21 05:22
@engram-design it worked!

**Comment by florentineprinzessinzusachsen** [comment] 2018-02-21 08:25
@engram-design FYI, when using dev-craft-3 the initial migrations work for me, when I manually rename all supertablecontent_* to stc_* **after** the initial craft 2>3 migration and **before** the supertables migration.

Thank you a lot for your help and for Supertables!

verbb/super-table dev-craft-3 (323f386)
craftcms/cms 3.0.0-RC11

**Comment by engram-design** [comment] 2018-02-21 08:29
@florentineprinzessinzusachsen So the migration won't work unless you rename those database tables?

**Comment by florentineprinzessinzusachsen** [comment] 2018-02-21 08:41
@engram-design correct! But I had to do that since your initial commit of Supertables for Craft 3 so I wrote a script for that ;) Let me know if I can assist.

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'craf_supertableconte_58_headlinesubheadlinebut_elementI_local_fk'; check that column/key exists
The SQL being executed was: DROP INDEX craf_supertableconte_58_headlinesubheadlinebut_elementI_local_fk ON craft_supertablecontent_58_headlinesubheadlinebutton

Migration: verbb\supertable\migrations\m180210_000000_migrate_content_tables
```
```
CREATE TABLE `craft_supertablecontent_58_headlinesubheadlinebutton` (
  `id` int(11) NOT NULL,
  `elementId` int(11) NOT NULL,
  `locale` char(12) COLLATE utf8_unicode_ci NOT NULL,
  `locale__siteId` int(11) NOT NULL,
  `field_headline` text COLLATE utf8_unicode_ci,
  `field_subheadline` text COLLATE utf8_unicode_ci,
  `field_colorHeadlineSubheadline` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `field_buttonLink` text COLLATE utf8_unicode_ci,
  `field_buttonIcon` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'none',
  `field_position` varchar(255) COLLATE utf8_unicode_ci DEFAULT 'middleCenter',
  `field_showPostDate` tinyint(1) UNSIGNED NOT NULL DEFAULT '0',
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `craft_supertablecontent_58_headlinesubheadlinebutton`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `craf_supertablecont_58_headlinesubheadlineb_element_local_un_id` (`elementId`,`locale`),
  ADD KEY `craft_supertablecontent_58_headlinesubheadlinebutton_locale_fk` (`locale`),
  ADD KEY `craft_supertableconte_58_headlinesubheadlinebutt_local_siteI_fk` (`locale__siteId`);
```

**Comment by engram-design** [comment] 2018-02-21 08:52
@florentineprinzessinzusachsen Ideally, I'd like to fix that. I wonder if I can get a copy of your database? Are you on Slack?

**Comment by engram-design** [comment] 2018-02-21 09:25
@florentineprinzessinzusachsen This should be fixed in the 2.0.4 released, which has been directly modified to include these fixes (which threw fatal errors in migrations).

**Closed as completed by engram-design** 2018-02-21 09:25 UTC

**Comment by florentineprinzessinzusachsen** [comment] 2018-02-21 09:33
Sorry I didn't get back in time. 
But seems you have figured it out. Migrations runs flawlessly now. Thank you very much!

**Comment by engram-design** [comment] 2018-02-21 09:44
Thanks for both your help - very much appreciated!
