### ISSUE TITLE
Removing a Super Table field doesn't always remove the associated table

### ISSUE THREAD

**Issue by lukehmu** [engram-design/SuperTable#129] opened 2018-03-02 11:32 UTC
### Description
Through a failed Super Table migration (updating between 2.0.3 > 2.0.4), we discovered that a field that we had removed (inside a Matrix block) hadn't deleted the table.

We got the following error on 'Finishing up':
```
One of Super Table’s migrations failed.

Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (epwebsit_bli55.#sql-2140_3c047c, CONSTRAINT craft_stc_22_mxfsimplelinks_elementId_fk FOREIGN KEY (elementId) REFERENCES craft_elements (id) ON DELETE CASCADE)
The SQL being executed was: ALTER TABLE craft_stc_22_mxfsimplelinks ADD CONSTRAINT craft_stc_22_mxfsimplelinks_elementId_fk FOREIGN KEY (elementId) REFERENCES craft_elements (id) ON DELETE CASCADE

Migration: verbb\supertable\migrations\m180219_000000_sites
```

Our local environment correctly removed the table `craft_stc_22_simplelinks` when we removed the field.

When we did this on our staging env, we also deleted the field, but after the migration fail above, we realised that the process here did not remove the table.

We haven't been able to replicate this issue, but we fixed it by manually removing the `craft_stc_22_simplelinks` table.

### Additional info

- Plugin version: 2.0.3 > 2.0.4
- Craft version: Craft Pro 3.0.0-RC13

**Comment by engram-design** [comment] 2019-02-10 11:20
Going to close this due to lack of being able to reproduce this. Please ping me to reopen if still an issue.

**Closed as completed by engram-design** 2019-02-10 11:20 UTC
