### ISSUE TITLE
Attempting to duplicate an unsaved element.

### ISSUE THREAD

**Issue by marknotton** [engram-design/SuperTable#380] opened 2020-08-13 15:48 UTC
When using SuperTables within a [Neos field](https://github.com/spicywebau/craft-neo), saving an entry will throw an "Attempting to duplicate an unsaved element." It does not happen if there were no content changes to the entry; however changes to **any** field within a Neos block will still throw the error. When I remove my SuperTable field from Neo everything works as normal. 

- Plugin version: 2.6.1
- Neo Fields Plugin version: 2.8.4 
- Craft version: 3.5.2 and 3.5.3
- Multi-site: No

```
yii\base\Exception: Attempting to duplicate an unsaved element. in /Website/vendor/craftcms/cms/src/services/Elements.php:888
Stack trace:
#0 /Website/vendor/verbb/super-table/src/services/SuperTableService.php(895): craft\services\Elements->duplicateElement(Object(verbb\supertable\elements\SuperTableBlockElement), Array)
#1 /Website/vendor/verbb/super-table/src/fields/SuperTableField.php(1025): verbb\supertable\services\SuperTableService->duplicateBlocks(Object(verbb\supertable\fields\SuperTableField), Object(benf\neo\elements\Block), Object(benf\neo\elements\Block), true)
#2 /Website/vendor/craftcms/cms/src/base/Element.php(3164): verbb\supertable\fields\SuperTableField->afterElementPropagate(Object(benf\neo\elements\Block), true)
#3 /Website/vendor/craftcms/cms/src/services/Elements.php(1053): craft\base\Element->afterPropagate(true)
#4 /Website/vendor/spicyweb/craft-neo/src/services/Fields.php(347): craft\services\Elements->duplicateElement(Object(benf\neo\elements\Block), Array)
#5 /Website/vendor/spicyweb/craft-neo/src/Field.php(655): benf\neo\services\Fields->duplicateBlocks(Object(benf\neo\Field), Object(craft\elements\Entry), Object(craft\elements\Entry), true)
#6 /Website/vendor/craftcms/cms/src/base/Element.php(3164): benf\neo\Field->afterElementPropagate(Object(craft\elements\Entry), true)
#7 /Website/vendor/craftcms/cms/src/elements/Entry.php(1473): craft\base\Element->afterPropagate(true)
#8 /Website/vendor/craftcms/cms/src/services/Elements.php(1053): craft\elements\Entry->afterPropagate(true)
#9 /Website/vendor/craftcms/cms/src/services/Revisions.php(156): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#10 /Website/vendor/craftcms/cms/src/elements/Entry.php(1477): craft\services\Revisions->createRevision(Object(craft\elements\Entry), 1, NULL)
#11 /Website/vendor/craftcms/cms/src/services/Elements.php(2372): craft\elements\Entry->afterPropagate(false)
#12 /Website/vendor/craftcms/cms/src/services/Elements.php(691): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#13 /Website/vendor/craftcms/cms/src/controllers/EntriesController.php(380): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#14 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#15 /Website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /Website/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#17 /Website/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('save-entry', Array)
#18 /Website/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#19 /Website/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('entries/save-en...', Array)
#20 /Website/vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction('entries/save-en...', Array)
#21 /Website/vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /Website/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /Website/web/index.php(14): yii\base\Application->run()
#24 {main}
```

**Comment by GaryReckard** [comment] 2020-08-13 17:42
I'm experiencing this issue on:

- Craft v3.4.30
- Neo v2.7.25
- SuperTable v2.5.4
- Multisite: yes

**Comment by ttempleton** [comment] 2020-08-14 07:33
Possible Neo bug (spicywebau/craft-neo#352), not really certain at this stage as I haven't been able to reproduce the error.  Will share any information I find out here if I can make any further progress on it.

**Comment by engram-design** [comment] 2020-08-17 23:46
Thanks @ttempleton looking into it on my end as well.

**Comment by marknotton** [comment] 2020-08-18 06:38
An example of the SuperTable I'm attempting to use might help you reproduce the error. The field in question contains a Plain Text, Two tables, and a Lightswitch. The error only happens if the SuperTable field is used in more than one NeoField block. 

<img width="840" alt="Screenshot 2020-08-18 at 07 28 59" src="https://user-images.githubusercontent.com/4622921/90478436-10326880-e125-11ea-82bb-83ed106f568a.png">

_Not sure if I should be crossposting this to @ttempleton issue too?_

**Comment by ttempleton** [comment] 2020-09-05 06:01
Neo 2.8.8 should fix this.  This was happening when an otherwise-unmodified Neo block had a Super Table field added to it with either a minimum number of rows set or a static row.  Because the Neo block was otherwise unmodified, it was not being resaved, so the new Super Table rows were never being saved.  Neo should now set such Neo blocks as modified, so the block, and therefore the new Super Table content, is saved.

**Comment by engram-design** [comment] 2020-09-05 07:03
Nice one @ttempleton closing for now, but please comment if this still continues to be an issue.

**Closed as completed by engram-design** 2020-09-05 07:03 UTC

**Comment by marknotton** [comment] 2020-09-07 07:24
Fantastic! Thanks for troubleshooting and resolving this so promptly @ttempleton
