### ISSUE TITLE
Undefined index: handle when used in a Matrix field

### ISSUE THREAD

**Issue by louderthan10** [engram-design/SuperTable#1] opened 2015-05-06 00:08 UTC
Hi guys,

I'm running into an issue where some entries are getting an error when they contain a Matrix block with your field in it. Specifically in this case, the same Matrix block has a standard table, which is populated with data, and has a supertable which is not populated (not sure if that's relevant).

![screen shot 2015-05-05 at 16 54 24](https://cloud.githubusercontent.com/assets/49751/7485250/73854604-f347-11e4-93e3-8a96d55a686c.png)

If I remove the supertable field from the Matrix, the entry works again.

**Comment by engram-design** [comment] 2015-05-06 00:19
Hmm - seems interesting that the error is being thrown by `TableFieldType.php`, and not `SuperTableFieldType.php`.

Anyway, I've attached a few screenshots of what I've got going, and have tested working. Can you confirm, or let me know if its not correct?

Alternatively - just post some screenshots of your Matrix layout :)
![screen shot 2015-05-06 at 10 19 22 am](https://cloud.githubusercontent.com/assets/1221575/7485454/656d048e-f3d9-11e4-9bfc-af154c9241e7.png)
![screen shot 2015-05-06 at 10 19 02 am](https://cloud.githubusercontent.com/assets/1221575/7485455/6572bcd0-f3d9-11e4-9235-1c1144974292.png)
![screen shot 2015-05-06 at 10 18 54 am](https://cloud.githubusercontent.com/assets/1221575/7485456/657359f6-f3d9-11e4-8969-3c392004a5f9.png)

**Comment by engram-design** [comment] 2015-05-25 19:52
@louderthan10 any further developments with the above?

**Comment by KnutSv** [comment] 2015-07-06 09:37
For me plain text fields inside table inside super table inside matrix seems to work fine, but once i try to use dropdown-fields or category-fields I can't retrive the data without getting error messages. For example for a dropdown field i get the "1" for all selections when i use `{{ block.field }}`. If I try to retrive `{{ block.field.value }}` or `{{ field.label }}` I get error messages like this:

```
Craft\SuperTable_BlockTypeModel and its behaviors do not have a method or closure named "value".
```

**Comment by engram-design** [comment] 2015-07-18 01:30
@KnutSv Sorry for the delay in getting back to you about this. I've been struggling to reproduce your error. See the below screenshots and code which works for me.

![screencapture-client-craft-dev-office-entries-homepage-2-homepage-1437182901347](https://cloud.githubusercontent.com/assets/1221575/8759762/2360a41a-2d40-11e5-9ac7-96143fb1b5b7.png)
![screencapture-client-craft-dev-office-settings-fields-edit-65-1437182656118](https://cloud.githubusercontent.com/assets/1221575/8759763/23637adc-2d40-11e5-8894-9683cf440565.png)
![screen shot 2015-07-18 at 11 24 27 am](https://cloud.githubusercontent.com/assets/1221575/8759764/23649b38-2d40-11e5-87bf-b235880ddb73.png)

```
{% for block in entry.matrixSuperTable %}
	{% for row in block.superTable %}
		{{ row.dropdown.label }}: {{ row.dropdown.value }}<br />
	{% endfor %}
{% endfor %}

Results in:

Option 1: Option 1
Option 2: Option 2
Option 2: Option 2
Option 1: Option 1
``

**Comment by KnutSv** [comment] 2015-07-27 13:14
Thanks, it turned out my issue was caused by using "type" as a handle. Changing the handle fixed the issue.

**Comment by rickprince** [comment] 2015-08-26 11:11
I'm getting this error too. Currently I'm getting it on SuperTableFieldType.php(78), but I've also seen the error for other blocks even though its when I'm adding a Super Table. 

I have a bunch of different blocks within a widget matrix block:
![image](https://cloud.githubusercontent.com/assets/4786843/9491942/87da8842-4c36-11e5-892c-3889fc9ea19b.png)

Which produces:
![image](https://cloud.githubusercontent.com/assets/4786843/9491887/edff223c-4c35-11e5-8ff5-e7785846c46e.png)

I'm using a fairly specific handle, so it can't be that. Any thoughts? Happy to share access  to my repo and db if it helps in reproducing the error. Thanks Josh!

**Comment by engram-design** [comment] 2015-08-26 12:22
@rickprince Interesting, I'd be interested to see your specific field setup. Probably best to get it touch via Slack, or send through an export of the field using [Field Manager](https://github.com/engram-design/FieldManager)

**Comment by engram-design** [comment] 2015-11-30 12:03
Closing for now - please reopen or create a new issue if you're still experiencing this.

**Closed by engram-design** 2015-11-30 12:03 UTC

**Comment by shealan** [comment] 2016-02-22 14:47
I'm running into this same issue. Latest Craft and Supertable. Line 79.

**Comment by engram-design** [comment] 2016-02-28 13:49
There are known issues with a Super Table / Matrix configuration and field handle validations. A Super Table field on its own will validate properly. This issue is usually due to a field using a reserved handle. @shealan are you able to confirm this? Happy to debug further in Slack?
