### ISSUE TITLE
Sprout Import Error

### ISSUE THREAD

**Issue by kmgdevelopment** [engram-design/SuperTable#235] opened 2019-02-02 20:45 UTC
Visiting the Sprout Import control panel page throws this error:

> Declaration of verbb\supertable\integrations\sproutimport\importers\fields\SuperTableImporter::getModelName() must be compatible with barrelstrength\sproutbase\app\import\base\Importer::getModelName(): string

It's coming from line 53 of `/craft/vendor/verbb/super-table/src/integrations/sproutimport/importers/fields/SuperTableImporter.php`

I'm currently running:

Craft 3.1.7
Super Table 2.1.6
Sprout Import 1.0.0-beta.20

**Comment by engram-design** [comment] 2019-02-02 21:50
I'll see what I can do about this, but from memory I don't think I even wrote this integration.

Wondering if @BenParizek might be able to shed some light on the changes?

**Comment by BenParizek** [comment] 2019-02-03 03:45
@engram-design I expect the issue is that we added some method hints recently:
https://github.com/barrelstrength/craft-sprout-base/blob/v4/src/app/import/base/Importer.php#L156

Adding the method hint `string` should resolve this.

```
public function getModelName(): string
{
  return SuperTableField::class;
}
```

**Comment by engram-design** [comment] 2019-02-09 11:34
Fixed in the latest craft-3 branch. If you'd like to trial this, run `composer require verbb/super-table:dev-craft-3`.

**Closed as completed by engram-design** 2019-02-09 11:34 UTC
