### ISSUE TITLE
SQL Error - Integrity constraint violation: 1062 Duplicate entry when propagating entries to new site

### ISSUE THREAD

**Issue by chadwells** [engram-design/SuperTable#409] opened 2021-04-20 18:26 UTC
I have several entry types that use a few different Super Table fields. I'm in the process of adding a new site to our config (making it now a multi-site config). When I add the site in Craft, and then edit an entry type that has a ST field to enable the entries for the new site, a job is queued up for propagation as expected. But it will fail with an SQL error.

An example:

1. We have an entry type for Dealers. There is an ST field in that entry type.
2. We add the new site, then edit the Entry type for "Dealer Entries", to enable the entries for this new site.
3. The "Resaving Dealer Entries entries" job is create and fails almost immediately, with the error:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '567638' for key 'craft_supertablecontent_showroompics_elementId_locale_unq_idx' The SQL being executed was: INSERT INTO `craft_stc_showroompics` (`elementId`, `siteId`, `field_showroomPicCropZoomLevel`, `dateCreated`, `dateUpdated`, `uid`) VALUES (567638, 2, '1.0', '2021-04-20 18:10:27', '2021-04-20 18:10:27', 'b03e8e7a-1cc4-4f74-9111-c59e5b5740a9')
```
![image](https://user-images.githubusercontent.com/7211456/115445132-73f4c000-a1e3-11eb-8240-88a4903ca95c.png)

I've tried the following:

1. Running both "Check Content Tables" and "Re-save Super Table Fields" in admin/super-table/settings.
2. Re-saving the entries before adding the new site.

**Steps to reproduce**
1. Add a new site
2. Edit an entry type with a Super Table field to enable it for the new site.

**Additional info**
- Plugin version: 2.6.7
- Craft version: 3.6.12
- Multi-site: Yes 

**Additional context**
I believe this sort of thing happens with any entry type that has a ST field on it (of note: these are NOT fields that are part of a Matrix field)

I believe these super table fields that are causing the error were created before we migrated to Craft 3 a couple years ago, if that helps.

Happy to give any additional info if needed. Thanks

**Comment by chadwells** [comment] 2021-04-20 19:51
Here's a stack trace for the example error above that also may help:

```
2021-04-20 15:44:32 - error - craft\queue\QueueLogBehavior::afterError
 [321745] Resaving Dealers Entries entries (attempt: 1, pid: 97) - Error (time: 0.983s): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '567638' for key 'craft_supertablecontent_showroompics_elementId_locale_unq_idx'
The SQL being executed was: INSERT INTO `craft_stc_showroompics` (`elementId`, `siteId`, `field_showroomPicCropZoomLevel`, `dateCreated`, `dateUpdated`, `uid`) VALUES (567638, 2, '1.0', '2021-04-20 19:44:32', '2021-04-20 19:44:32', 'a77dba8a-45e5-4596-bfb0-84b2fe601e09')
2021-04-20 15:44:32 - error - yii\db\IntegrityException
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '567638' for key 'craft_supertablecontent_showroompics_elementId_locale_unq_idx' in /app/cms/vendor/yiisoft/yii2/db/Command.php:1299
Stack trace:
#0 /app/cms/vendor/yiisoft/yii2/db/Command.php(1299): PDOStatement->execute()
#1 /app/cms/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /app/cms/vendor/craftcms/cms/src/helpers/Db.php(709): yii\db\Command->execute()
#3 /app/cms/vendor/craftcms/cms/src/services/Content.php(209): craft\helpers\Db::insert('{{%stc_showroom...', Array, true, Object(craft\db\Connection))
#4 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2500): craft\services\Content->saveContent(Object(verbb\supertable\elements\SuperTableBlockElement))
#5 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2714): craft\services\Elements->_saveElementInternal(Object(verbb\supertable\elements\SuperTableBlockElement), true, false)
#6 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2519): craft\services\Elements->_propagateElement(Object(verbb\supertable\elements\SuperTableBlockElement), Array, Object(verbb\supertable\elements\SuperTableBlockElement))
#7 /app/cms/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal(Object(verbb\supertable\elements\SuperTableBlockElement), false, true, true)
#8 /app/cms/vendor/verbb/super-table/src/services/SuperTableService.php(773): craft\services\Elements->saveElement(Object(verbb\supertable\elements\SuperTableBlockElement), false)
#9 /app/cms/vendor/verbb/super-table/src/fields/SuperTableField.php(1032): verbb\supertable\services\SuperTableService->saveField(Object(verbb\supertable\fields\SuperTableField), Object(craft\elements\Entry))
#10 /app/cms/vendor/craftcms/cms/src/base/Element.php(3359): verbb\supertable\fields\SuperTableField->afterElementPropagate(Object(craft\elements\Entry), false)
#11 /app/cms/vendor/craftcms/cms/src/elements/Entry.php(1580): craft\base\Element->afterPropagate(false)
#12 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2530): craft\elements\Entry->afterPropagate(false)
#13 /app/cms/vendor/craftcms/cms/src/services/Elements.php(821): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true)
#14 /app/cms/vendor/craftcms/cms/src/queue/jobs/ResaveElements.php(65): craft\services\Elements->resaveElements(Object(craft\elements\db\EntryQuery), false, true, true)
#15 /app/cms/vendor/yiisoft/yii2-queue/src/Queue.php(246): craft\queue\jobs\ResaveElements->execute(Object(craft\queue\Queue))
#16 /app/cms/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('321745', 'O:31:"craft\\que...', '3600', 1)
#17 /app/cms/vendor/craftcms/cms/src/queue/Queue.php(131): yii\queue\cli\Queue->handleMessage('321745', 'O:31:"craft\\que...', '3600', 1)
#18 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#19 /app/cms/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#20 /app/cms/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure))
#21 /app/cms/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#22 /app/cms/vendor/craftcms/cms/src/controllers/QueueController.php(105): craft\controllers\QueueController->actionRun()
#23 [internal function]: craft\controllers\QueueController->actionRetry()
#24 /app/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /app/cms/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#26 /app/cms/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('retry', Array)
#27 /app/cms/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('retry', Array)
#28 /app/cms/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('queue/retry', Array)
#29 /app/cms/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('queue/retry', Array)
#30 /app/cms/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#31 /app/cms/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#32 /app/cms/web/index.php(21): yii\base\Application->run()
#33 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '567638' for key 'craft_supertablecontent_showroompics_elementId_locale_unq_idx'
The SQL being executed was: INSERT INTO `craft_stc_showroompics` (`elementId`, `siteId`, `field_showroomPicCropZoomLevel`, `dateCreated`, `dateUpdated`, `uid`) VALUES (567638, 2, '1.0', '2021-04-20 19:44:32', '2021-04-20 19:44:32', 'a77dba8a-45e5-4596-bfb0-84b2fe601e09') in /app/cms/vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:
#0 /app/cms/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `cr...')
#1 /app/cms/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /app/cms/vendor/craftcms/cms/src/helpers/Db.php(709): yii\db\Command->execute()
#3 /app/cms/vendor/craftcms/cms/src/services/Content.php(209): craft\helpers\Db::insert('{{%stc_showroom...', Array, true, Object(craft\db\Connection))
#4 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2500): craft\services\Content->saveContent(Object(verbb\supertable\elements\SuperTableBlockElement))
#5 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2714): craft\services\Elements->_saveElementInternal(Object(verbb\supertable\elements\SuperTableBlockElement), true, false)
#6 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2519): craft\services\Elements->_propagateElement(Object(verbb\supertable\elements\SuperTableBlockElement), Array, Object(verbb\supertable\elements\SuperTableBlockElement))
#7 /app/cms/vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal(Object(verbb\supertable\elements\SuperTableBlockElement), false, true, true)
#8 /app/cms/vendor/verbb/super-table/src/services/SuperTableService.php(773): craft\services\Elements->saveElement(Object(verbb\supertable\elements\SuperTableBlockElement), false)
#9 /app/cms/vendor/verbb/super-table/src/fields/SuperTableField.php(1032): verbb\supertable\services\SuperTableService->saveField(Object(verbb\supertable\fields\SuperTableField), Object(craft\elements\Entry))
#10 /app/cms/vendor/craftcms/cms/src/base/Element.php(3359): verbb\supertable\fields\SuperTableField->afterElementPropagate(Object(craft\elements\Entry), false)
#11 /app/cms/vendor/craftcms/cms/src/elements/Entry.php(1580): craft\base\Element->afterPropagate(false)
#12 /app/cms/vendor/craftcms/cms/src/services/Elements.php(2530): craft\elements\Entry->afterPropagate(false)
#13 /app/cms/vendor/craftcms/cms/src/services/Elements.php(821): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, true)
#14 /app/cms/vendor/craftcms/cms/src/queue/jobs/ResaveElements.php(65): craft\services\Elements->resaveElements(Object(craft\elements\db\EntryQuery), false, true, true)
#15 /app/cms/vendor/yiisoft/yii2-queue/src/Queue.php(246): craft\queue\jobs\ResaveElements->execute(Object(craft\queue\Queue))
#16 /app/cms/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('321745', 'O:31:"craft\\que...', '3600', 1)
#17 /app/cms/vendor/craftcms/cms/src/queue/Queue.php(131): yii\queue\cli\Queue->handleMessage('321745', 'O:31:"craft\\que...', '3600', 1)
#18 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#19 /app/cms/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#20 /app/cms/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure))
#21 /app/cms/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#22 /app/cms/vendor/craftcms/cms/src/controllers/QueueController.php(105): craft\controllers\QueueController->actionRun()
#23 [internal function]: craft\controllers\QueueController->actionRetry()
#24 /app/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /app/cms/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#26 /app/cms/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('retry', Array)
#27 /app/cms/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('retry', Array)
#28 /app/cms/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('queue/retry', Array)
#29 /app/cms/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('queue/retry', Array)
#30 /app/cms/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#31 /app/cms/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#32 /app/cms/web/index.php(21): yii\base\Application->run()
#33 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '567638' for key 'craft_supertablecontent_showroompics_elementId_locale_unq_idx'
)

```

**Comment by chadwells** [comment] 2021-05-05 19:46
Hi, hoping to get some help with this... It's currently blocking our ability to turn our single-site implementation into a multisite one.

**Comment by davidwebca** [comment] 2021-05-06 04:21
Just leaving a comment to follow the topic. We just migrated a Craft 3.5 to 3.6 and Super Table complained about integrity constraint for one of our fields. It messed up the migration and crashed. We ended up with 2 fields named exactly the same, but I can't quite figure out how to get the fields to work again now. It seems when I delete one of the two, it deletes the "stc_" prefixed table that contains the content. In the admin, the field doesn't load anymore.

I'm sitting on this trying to figure out a way to fix back my database since I couldn't stop the client to update the live site. I see the data, just needs to link the entries / elements / stc_ table properly.

My field is called "flexibleImageCredits" so the table is called "stc_flexibleimagecredits" I weirdly can see two columns, one called "field_credits_old" containing my data and "field_credits" containing nothing. I'm getting the feeling that this is a migration crash issue and that the content in the "_old" should be in the new one, but even trying that, it doesn't work so I'm missing some piece of infos here.

**Comment by engram-design** [comment] 2021-05-19 06:46
So I've tried countless setups on my end to try and replicate this error, but I'm unable to. I'm wondering if you might be able to provide an export of your Super Table field using the Field Manager plugin.

The error is detecting there's already content for siteId `2` for the block with an ID of `567638`, so it's almost as if the propagation has already occurred.

@davidwebca Interested to know if you'd run the content table checker/fixer.

**Comment by chadwells** [comment] 2021-05-19 12:50
Hi @engram-design - Thanks for checking on this. Here is an export of that particular field (FYI - if I deleted this field and tried to add a site again, it would give the same error for another ST field)

```json
[
    {
        "name": "Showroom Pics",
        "handle": "showroomPics",
        "instructions": "Select \/ upload the image(s) to display for the showroom. If you add more than one image, they will be displayed in a carousel. Pic should be at least 2000px wide. For best results, please run the image through an optimizer (like ImageOptim for Mac or RIOT for Windows) before uploading.",
        "required": null,
        "searchable": 0,
        "translationMethod": "site",
        "translationKeyFormat": null,
        "type": "verbb\\supertable\\fields\\SuperTableField",
        "settings": {
            "minRows": null,
            "maxRows": null,
            "contentTable": "{{%stc_showroompics}}",
            "propagationMethod": "all",
            "staticField": null,
            "columns": {
                "1042": {
                    "width": ""
                },
                "1043": {
                    "width": ""
                }
            },
            "fieldLayout": "table",
            "selectionLabel": "Add an image",
            "placeholderKey": null,
            "blockTypes": {
                "new1": {
                    "fields": {
                        "new1": {
                            "name": "Showroom Pic",
                            "handle": "showroomPic",
                            "required": 1,
                            "instructions": "Pic should be at least 2000px wide. For best results, please run the image through an optimizer (like ImageOptim for Mac or RIOT for Windows) before uploading. ",
                            "searchable": 0,
                            "translationMethod": "site",
                            "translationKeyFormat": null,
                            "type": "craft\\fields\\Assets",
                            "typesettings": {
                                "useSingleFolder": true,
                                "allowUploads": true,
                                "defaultUploadLocationSource": "volume:cc8dfff9-abfc-407c-b9ed-586a2fb8805a",
                                "defaultUploadLocationSubpath": "",
                                "singleUploadLocationSource": "volume:0328a9c1-0519-4f03-a7c4-ddba6bcc7efa",
                                "singleUploadLocationSubpath": "",
                                "restrictFiles": 1,
                                "allowedKinds": [
                                    "image"
                                ],
                                "showUnpermittedVolumes": true,
                                "showUnpermittedFiles": false,
                                "previewMode": "full",
                                "sources": "*",
                                "source": null,
                                "targetSiteId": null,
                                "viewMode": "list",
                                "limit": 1,
                                "selectionLabel": "",
                                "showSiteMenu": true,
                                "localizeRelations": false,
                                "validateRelatedElements": false,
                                "allowSelfRelations": false
                            }
                        },
                        "new2": {
                            "name": "Crop Zoom Level",
                            "handle": "showroomPicCropZoomLevel",
                            "required": 0,
                            "instructions": "When the showroom pic is displayed on certain smaller screen sizes, it is cropped square, preserving the Focus Point that you set on the image. Sometimes, you may want to also have it zoom in on the image a bit before cropping. Set that level here.",
                            "searchable": 0,
                            "translationMethod": "none",
                            "translationKeyFormat": null,
                            "type": "craft\\fields\\Dropdown",
                            "typesettings": {
                                "optgroups": true,
                                "options": [
                                    {
                                        "label": 1,
                                        "value": 1,
                                        "default": 1
                                    },
                                    {
                                        "label": 1.25,
                                        "value": 1.25,
                                        "default": ""
                                    },
                                    {
                                        "label": 1.5,
                                        "value": 1.5,
                                        "default": ""
                                    },
                                    {
                                        "label": 1.75,
                                        "value": 1.75,
                                        "default": ""
                                    },
                                    {
                                        "label": 2,
                                        "value": 2,
                                        "default": ""
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    }
]
```

**Comment by davidwebca** [comment] 2021-05-19 15:12
@engram-design What is that table fixer you're mentioning? Sorry if it's obvious, I don't think I've heard of it.

**Comment by jmcgaha** [comment] 2021-05-28 19:56
I got a very similar error on Craft 3.6.13 and SuperTable 2.6.7.

I was not creating a new site but a new supertable field. I'm not sure exactly when the failed queue item occurred - whether it was creating the field, changing a field setting or adding it to the entry type. I just know that once I tried to save the entry with the new field super table field, I was unable to save it.

I tried both of the utilities to fix supertables in the settings area but neither one fixed the issue. I ended up just restoring from a backup and recreating the fields without Supertable to get by.

This is the output on one of the queue items.
```SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '202840' for key 'PRIMARY' The SQL being executed was: INSERT INTO `supertableblocks` (`id`, `fieldId`, `ownerId`, `typeId`, `sortOrder`, `dateCreated`, `dateUpdated`, `uid`) VALUES (202840, 319, 538, 35, 1, '2021-05-28 17:35:25', '2021-05-28 17:35:25', '11ffab0a-f2e5-42dc-a34e-396688ea306a') ```

**Comment by engram-design** [comment] 2021-05-30 06:52
@davidwebca The content table checker/fixer is under Settings > Super Table. Refer to https://github.com/verbb/super-table#updating-to-craft-31

Thanks also for the input @jmcgaha

**Comment by engram-design** [comment] 2021-05-30 07:28
@chadwells Still can't replicate this one. Can you shoot through your composer.lock and composer.json files so I can hopefully replicate your setup? Wondering if it might be a conflicting plugin.

Feel free to shoot them through to `web at verbb.io`

**Comment by chadwells** [comment] 2021-06-01 11:54
Hi @engram-design -- Just sent those files to you. Please let me know if there is anything else I can provide. Thanks

**Comment by jmcgaha** [comment] 2021-07-06 15:57
Just wondering if there is any update on this. I had it occur on staging per my comment from May and were able to replace with a fresh db from production and it didn't occur again. We're just kind of gun-shy now to touch any super tables until we know this issue won't happen again.

**Comment by chadwells** [comment] 2021-07-08 14:35
Hello @engram-design -- really needing to get this issue resolved one way or another as we are unable to switch this site to multi-site until it is resolved. I'm available to assist in any way necessary, just let me know!

**Comment by engram-design** [comment] 2021-07-09 05:37
@chadwells I believe I was waiting for a reply from my last email to you?

**Comment by chadwells** [comment] 2021-07-09 12:22
@engram-design My apologies, but I don't see any followup emails from you after I sent over the requested composer files.

**Comment by engram-design** [comment] 2021-07-10 05:42
Hmmm, I replied to your email just after sending this message, so odd. My response:

> I should’ve asked you to send your config/project folder too - sorry! At least that way I can see the field setup. However, nothing an issue so far with the same plugins. Failing that, I don’t suppose it’d be possible to get a copy of your database? Totally understand if you can’t share it though.

**Comment by chadwells** [comment] 2021-08-05 17:48
@engram-design - Thanks. I've sent you an email with some links to those things.

**Comment by arjankruithof** [comment] 2021-09-08 11:53
Any updates on this? I already had a multisite, but i added extra websites..

Now the CMS tries to write to an existing ID, instead for an available ID. The index seems to be wrong.

```Duplicate entry '75831' for key 'PRIMARY' The SQL being executed was: INSERT INTO `craft_supertableblocks` (`id`, `fieldId`, `ownerId`, `typeId`, `sortOrder`, `dateCreated`, `dateUpdated`, `uid`) VALUES (75831, 210, 702, 15, 1, '2021-09-08 06:36:51', '2021-09-08 06:36:51', '9cb75ad7-a6ab-46ae-9e17-10c81e02182f')```

This table goes up to ID 86000 or so.

**Comment by gbowne-quickbase** [comment] 2021-11-17 22:48
We're still seeing this issue in 3.7.18.2, and Super Table 2.6.8, and it looks like we're having the same type of error that others are reporting: 
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1265960' for key 'craft_supertablecontent_97_spantexts_elementId_locale_unq_idx' The SQL being executed was: INSERT INTO `craft_stc_97_spantexts` (`elementId`, `siteId`, `field_imageAltText`, `field_header`, `field_body`, `field_dingbat`, `field_cta1Link`, `field_cta1Type`, `field_cta2Link`, `field_cta2Type`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1265960, 2, NULL, NULL, NULL, 0, '[]', 'Cta--primary-btn', '[]', 'Cta--primary-btn', '2021-11-17 22:47:03', '2021-11-17 22:47:03', 'e59f1f04-1c41-401a-953b-871545a8af3f')
```
We have run both of the fixers within the plugin, and still are getting that issue.
We even tried running the `fix-fk` plugin from Pixel and Tonic, but no 🎲 dice

**Comment by gbowne-quickbase** [comment] 2021-12-01 21:06
Looking at these error messages, it makes me think that either:
* the index should have a unique constraint for both `id` and `siteId` but only has `id` OR
* the content has already been inserted by another process and the plugin is trying to duplicate it again.

**Comment by engram-design** [comment] 2021-12-02 02:48
Are you able to update to [2.7.0](https://github.com/verbb/super-table/releases/tag/2.7.0) to test?

**Comment by gbowne-quickbase** [comment] 2021-12-02 13:54
Running 2.7.0 I still get similar errors on trying to save a page with existing SuperTable fields. 
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2643277' for key 'craft_supertableconten_104_displayconten_elementId_locale_unq_id' The SQL being executed was: INSERT INTO `craft_stc_104_displaycontent` (`elementId`, `siteId`, `field_header`, `field_body`, `dateCreated`, `dateUpdated`, `uid`) VALUES (2643277, 2, 'This is a test', 'Section config is used to configure attributes about this section for use in sticky-navs and other dynamic features that may be included on this page. It is highly recommended to enter values here, though it is not required.', '2021-12-02 13:32:32', '2021-12-02 13:32:32', '0428e519-0a20-4608-81c5-33fe03383c22')
```

The duplicate constraint is only about the `elementId` and not the `siteId` as well. So looking at the table itself:

```
PRIMARY KEY (`id`),
  UNIQUE KEY `craft_supertableconten_104_displayconten_elementId_locale_unq_id` (`elementId`),
  KEY `craft_supertablecontent_104_displaycontent_locale__siteId_fk` (`siteId`),
  CONSTRAINT `craft_supertablecontent_104_displaycontent_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `craft_elements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `craft_supertablecontent_104_displaycontent_locale__siteId_fk` FOREIGN KEY (`siteId`) REFERENCES `craft_sites` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
```

It seems that the UNIQUE KEY should be (`elementId`,`siteId`)
How would we set that up to test it? @engram-design

**Comment by gbowne-quickbase** [comment] 2021-12-02 15:59
Okay. When I created a new UNIQUE KEY for as specified above (elementId, siteId) and then dropped the original one, BOOM that error disappeared and the next field down the line was the error. This is what I did to change the UNIQUE KEY.
```
alter table craft_stc_104_displaycontent add unique key craft_supertablecont_104_displaycont_elementId_locale_unq_id (elementId, siteId);
alter table craft_stc_104_displaycontent drop index craft_supertableconten_104_displayconten_elementId_locale_unq_id;
```
You could even do this by throwing in some `rename index` commands along the way: in pseudo code
``` 
alter table [name] rename index [current-element-locale-unique] to [delete me soon];
alter table [name] add unique key [current-element-locale-unique] (elementId, siteId);
alter table [name] drop index [delete me soon];
```

**Comment by gbowne-quickbase** [comment] 2021-12-02 16:29
Looking further, it seems that `m180219_000000_sites.php` was set up to do this 
https://github.com/verbb/super-table/blob/8926b403b2968507ad4aad95f660f6a77d7236b8/src/migrations/m180219_000000_sites.php#L99
But it looks like that didn't happen in my DB anywhere, or others for that matter. 
I'm not sure if 
https://github.com/verbb/super-table/blob/8926b403b2968507ad4aad95f660f6a77d7236b8/src/migrations/CreateSuperTableContentTable.php#L22
is being run, which would do the same thing.

**Comment by engram-design** [comment] 2021-12-02 20:05
So the `craft_supertablecontent_` content tables are the old format, from a long time ago, before they were changed to `craft_stc_` to get around MySQL table name length - it seems odd that your errors point to that content table? Have you run the content table checker/fixer?

If that migration hasn't been run properly (worth checking in your `migrations` db table), then there's probably bigger issues around the corner.

**Comment by gbowne-quickbase** [comment] 2021-12-02 23:06
Thanks for looking into this @engram-design. It looks like both me and the OP have unique constraints/indexes that have the old long format names in them, but the tables were adjusted along the way. Is there a particular migration we'd need to re-run? And would just deleting that row from the migrations table kick that off again?

**Comment by engram-design** [comment] 2021-12-03 02:18
So the content table fixer _should_ take care of that, but maybe I need to setup another migration specifically for this to run on-demand. It's unfortunately a bit complicated as this is going back several years (2018), so it's probably not as simple as pointing you to a single migration you need to run.

And deleting the row from the migrations table won't be enough, as Craft needs to notice a schema change with the plugin. However even if you do this yourself by editing the plugin file, or your project config yaml files, you'll get out of sync with the plugin releases.

I might have to put something together for you to run the migration. You can trigger a migration on-demand, but the migration probably expects your tables and structure in a Craft 2 format, as opposed to how you have it now.

If you're up for it, sending your database entirely to `web at verbb.io` would really help, as I can tailor the fix to your site (and hopefully others here), along with how to reproduce it. But understand if you're unable to share.

**Comment by gbowne-quickbase** [comment] 2021-12-03 11:54
Thanks for the attention on this, really. I'll send you a link to the DB. Since it's already the weekend for you, I might take a bit of time to see if I can craft a solution to go into your Fix Content Tables method that will look for these missed unique keys and rebuild them. It'll give me a chance to get better at yii. If I figure something out, I'll make a PR.

**Comment by chadwells** [comment] 2021-12-22 14:32
Hi @engram-design, Was wondering the status of reviewing @gbowne-quickbase's PR? We are still experiencing the original issue and we are desperate to get this resolved. It does make sense that it affects sites that were "early adopters" of Craft and Super Table. So many things have changed since 2015! I'm willing to assist with testing this in any way. Just let me know. Thanks!

**Comment by engram-design** [comment] 2021-12-29 02:52
@chadwells Have just reviewed and merged this PR, should be in the next release.

**Closed as completed** 2021-12-29 02:52 UTC
